name: CI
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Configure git for private modules
        run: git config --global url."https://${{ secrets.RELEASES_TOKEN }}@github.com/".insteadOf "https://github.com/"
      - run: go build ./...
        env:
          GOPRIVATE: github.com/GoCodeAlone/*
          GONOSUMCHECK: github.com/GoCodeAlone/*
      - run: go test ./... -v -race -count=1
        env:
          GOPRIVATE: github.com/GoCodeAlone/*
          GONOSUMCHECK: github.com/GoCodeAlone/*
